try:
    raise ValueError("hello world!")
except Exception:
    print(Exception)




